### ISSUE TITLE
x86_64-linux-gnu-gcc'failed with exit status 1

### ISSUE THREAD

**Issue by sowhi** [hszhao/PointWeb#8]
Hi,sorry to bother you.When i used the command“ python setup.py install”,I encontered warnings like this:Tensor.data<T>() is deprecated,and lastly met the error:command'x86_64-linux-gnu-gcc'failed with exit status 1".Hoping your answer,thanks very much.

**Comment by wangkai19961223** [comment]
I had a similar problem “”command gcc  failed with exit status 1“”，Have you solved your problem yet？if so ,please tell me your solution!!!

**Comment by largeword** [comment]
> I had a similar problem “”command gcc failed with exit status 1“”，Have you solved your problem yet？if so ,please tell me your solution!!!

install python with version 3.6, then use this command to install pytorch `pip install torch==1.4.0+cu100 torchvision==0.5.0+cu100 torchaudio===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html`

Note that, 1.4.0 version of pytorch is the only one fits this project in my attempts. If use `conda install` to install pytorch, may encounter an error missing cuda_cmake_macros.h during the compiling.
